# name: 'Komari'

[light]
# preferred_background: f0f0dc
fish_color_normal 050504
fish_color_autosuggestion 8c3c50
fish_color_command 8c3c50
fish_color_keyword a03c50
fish_color_quote f0a03c
fish_color_redirection b43c3c
fish_color_end f0f104
fish_color_error f10504
fish_color_param 050504
fish_color_comment 8c3c50
fish_color_operator a03c50
fish_color_escape f0a03c
fish_color_cwd 050504
fish_color_cwd_root f10504
fish_color_host 8c3c50
fish_color_host_remote a03c50
fish_color_user 050504
fish_color_match --background=f0f104
fish_color_selection --background=f0f0dc --foreground=050504

[dark]
# preferred_background: 050504
fish_color_normal f0f0dc
fish_color_autosuggestion 8c3c50
fish_color_command f0f104
fish_color_keyword f0a03c
fish_color_quote f0a03c
fish_color_redirection b43c3c
fish_color_end f0f104
fish_color_error f10504
fish_color_param f0f0dc
fish_color_comment 8c3c50
fish_color_operator a03c50
fish_color_escape f0a03c
fish_color_cwd f0f0dc
fish_color_cwd_root f10504
fish_color_host f0f0dc
fish_color_host_remote f0a03c
fish_color_user f0f0dc
fish_color_match --background=f0f104 --foreground=050504
fish_color_selection --background=a03c50 --foreground=f0f0dc

[unknown]
fish_color_normal --reset
fish_color_autosuggestion brblack
fish_color_cancel -r
fish_color_command --reset
